name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: renegades-draft-central/package-lock.json

    - name: Install dependencies
      run: npm ci
      working-directory: renegades-draft-central

    - name: Run ESLint
      run: npm run lint
      working-directory: renegades-draft-central

    - name: Run tests
      run: npm run test:run
      working-directory: renegades-draft-central

    - name: Check build
      run: npm run build
      working-directory: renegades-draft-central